`timescale 1ns/1ps

module axi_master #(
    parameter ADDR_WIDTH = 32,
    parameter DATA_WIDTH = 32,
    parameter ID_WIDTH   = 4,
    parameter USER_WIDTH = 1
)(
    input wire clk, 
    input wire rst,
    input wire start_write, 
    input wire [ADDR_WIDTH-1:0] write_addr,
    input wire [7:0] write_len, 
    input wire [ID_WIDTH-1:0] write_id,
    input wire [USER_WIDTH-1:0] write_user,
    input wire [DATA_WIDTH-1:0] write_data,
    input wire [(DATA_WIDTH/8)-1:0] write_strb,
    input wire write_data_valid, 
    output wire write_data_ready,
    output wire write_busy, 
    output wire write_done, 
    output wire [1:0] write_resp,
    output wire [ID_WIDTH-1:0] write_resp_id,
    output wire [USER_WIDTH-1:0] write_resp_user,
    output wire [ID_WIDTH-1:0] m_axi_awid,
    output wire [ADDR_WIDTH-1:0] m_axi_awaddr, 
    output wire [7:0] m_axi_awlen,
    output wire [2:0] m_axi_awsize, 
    output wire [1:0] m_axi_awburst,
    output wire [USER_WIDTH-1:0] m_axi_awuser, 
    output wire m_axi_awvalid,
    input wire m_axi_awready,
    output wire [DATA_WIDTH-1:0] m_axi_wdata,
    output wire [(DATA_WIDTH/8)-1:0] m_axi_wstrb, 
    output wire m_axi_wlast,
    output wire [USER_WIDTH-1:0] m_axi_wuser, 
    output wire m_axi_wvalid,
    input wire m_axi_wready,
    input wire [ID_WIDTH-1:0] m_axi_bid, 
    input wire [1:0] m_axi_bresp,
    input wire [USER_WIDTH-1:0] m_axi_buser, 
    input wire m_axi_bvalid,
    output wire m_axi_bready,

    input wire start_read, 
    input wire [ADDR_WIDTH-1:0] read_addr,
    input wire [7:0] read_len, 
    input wire [ID_WIDTH-1:0] read_id,
    input wire [USER_WIDTH-1:0] read_user,
    output wire [DATA_WIDTH-1:0] read_data,
    output wire [(DATA_WIDTH/8)-1:0] read_strb, 
    output wire read_data_valid,
    output wire read_data_last, 
    input wire read_data_ready,
    output wire read_busy, 
    output wire read_done, 
    output wire [1:0] read_resp,
    output wire [ID_WIDTH-1:0] read_resp_id,
    output wire [USER_WIDTH-1:0] read_resp_user,
    output wire [ID_WIDTH-1:0] m_axi_arid,
    output wire [ADDR_WIDTH-1:0] m_axi_araddr, 
    output wire [7:0] m_axi_arlen,
    output wire [2:0] m_axi_arsize, 
    output wire [1:0] m_axi_arburst,
    output wire [USER_WIDTH-1:0] m_axi_aruser, 
    output wire m_axi_arvalid,
    input wire m_axi_arready,
    input wire [ID_WIDTH-1:0] m_axi_rid, 
    input wire [DATA_WIDTH-1:0] m_axi_rdata,
    input wire [1:0] m_axi_rresp, 
    input wire m_axi_rlast,
    input wire [USER_WIDTH-1:0] m_axi_ruser, 
    input wire m_axi_rvalid,
    output wire m_axi_rready
);
    axi_write_master #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH), .ID_WIDTH(ID_WIDTH), .USER_WIDTH(USER_WIDTH)) u_write (
        .clk(clk), .rst(rst), .start_write(start_write), .write_addr(write_addr), .write_len(write_len), .write_id(write_id), .write_user(write_user),
        .write_data(write_data), .write_strb(write_strb), .write_data_valid(write_data_valid), .write_data_ready(write_data_ready), .write_busy(write_busy), .write_done(write_done), .write_resp(write_resp), .write_resp_id(write_resp_id), .write_resp_user(write_resp_user),
        .m_axi_awid(m_axi_awid), .m_axi_awaddr(m_axi_awaddr), .m_axi_awlen(m_axi_awlen), .m_axi_awsize(m_axi_awsize), .m_axi_awburst(m_axi_awburst), .m_axi_awuser(m_axi_awuser), .m_axi_awvalid(m_axi_awvalid), .m_axi_awready(m_axi_awready), .m_axi_wdata(m_axi_wdata), .m_axi_wstrb(m_axi_wstrb), .m_axi_wlast(m_axi_wlast), .m_axi_wuser(m_axi_wuser), .m_axi_wvalid(m_axi_wvalid), .m_axi_wready(m_axi_wready), .m_axi_bid(m_axi_bid), .m_axi_bresp(m_axi_bresp), .m_axi_buser(m_axi_buser), .m_axi_bvalid(m_axi_bvalid), .m_axi_bready(m_axi_bready));
    axi_read_master #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH), .ID_WIDTH(ID_WIDTH), .USER_WIDTH(USER_WIDTH)) u_read (
        .clk(clk), .rst(rst), .start_read(start_read), .read_addr(read_addr), .read_len(read_len), .read_id(read_id), .read_user(read_user), .read_data(read_data), .read_strb(read_strb), .read_data_valid(read_data_valid), .read_data_last(read_data_last), .read_data_ready(read_data_ready), .read_busy(read_busy), .read_done(read_done), .read_resp(read_resp), .read_resp_id(read_resp_id), .read_resp_user(read_resp_user), .m_axi_arid(m_axi_arid), .m_axi_araddr(m_axi_araddr), .m_axi_arlen(m_axi_arlen), .m_axi_arsize(m_axi_arsize), .m_axi_arburst(m_axi_arburst), .m_axi_aruser(m_axi_aruser), .m_axi_arvalid(m_axi_arvalid), .m_axi_arready(m_axi_arready), .m_axi_rid(m_axi_rid), .m_axi_rdata(m_axi_rdata), .m_axi_rresp(m_axi_rresp), .m_axi_rlast(m_axi_rlast), .m_axi_ruser(m_axi_ruser), .m_axi_rvalid(m_axi_rvalid), .m_axi_rready(m_axi_rready));
endmodule